server:
  port: ${CODELOOM_PORT:8080}
  error:
    include-stacktrace: never

spring:
  application:
    name: backend
  datasource:
    url: ${CODELOOM_DB_URL}
    username: ${CODELOOM_DB_USER}
    password: ${CODELOOM_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
springdoc:
  api-docs:
    path: /docs/api
  swagger-ui:
    path: /docs/swagger.html